# Site settings
标题：Tan博客
SEOTitle：老谭的博客|Tan博客
header-img:IMG/home-bg.jpg
电子邮件:tanz755465@gmail.com
描述:"这里是@老谭 的个人博客，与你一起发现更大的世界|要做一个有swag的程序员"
关键字:"黄玄，胡克黄玄，胡克，鬼栈，huxpro，@huxpro，黄玄的博客，Hux博客，博客，个人网站，互联网，Web、JavaScript、React、React Native、前端，设计"
URL："https://tanz8.github.io" #您的主机，用于绝对URL
baseUrl：“”#例如，"/blog"(如果您的日志位于"主机/博客"上)

#发布具有未来日期的帖子或集合文档。
未来:正确

#SNS设置
RSS：假的
微博用户名(_U)：huxpro
知乎_用户名：huxpro
GitHub_username:huxpro
Twitter_username:huxpro
#facebook_username:huxpro
#linkedin_username:firstname-lastname-idxxxx

#生成设置
#从2016年开始，GitHub页面不支持“pygments”。请使用“胭脂”来突出显示。
荧光笔:胭脂
永久链接:漂亮的
分页:10
排除:
  [
    "更少",
    "节点模块",
    "Gruntfile.js",
    "包.JSON",
    "README.md",
    "README.zh.md",
  ]
anchorjs：正确#如果要自定义锚，请签出行：'Post.html'的181
#如果您在中国遇到时区问题(例如#68)，请取消注释以使用以下内容：
#时区：中国大陆

#宝石
#来自PR#40，支持Jekyll3.0的本地预览
#确保已安装此gem
#'$gem安装jekyll-paginate'
插件:[哲基尔-浆状]

#降价设置
#把红地毯换成克拉姆当，
#虽然红地毯可以自动突出显示代码，但缺少header-id使目录不可能，所以我切换到克拉姆当
#文档：http://jekyllrb.com/docs/configuration/#kramdown
降价:克拉姆当
克拉姆当:
输入：GFM#使用GitHub风味降价！重要的
语法_荧光笔_opts:
跨度:
行号(_N)：假的
块:
行号(_N)：正确
起始线(_L)：1

#Disqus设置
Disqus_username:Hux

#网易设置
网易_comment:假的

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
